spring:
  datasource:
    username: postgres
    password: datetime_example
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=datetime_example


  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
#        jdbc:
#          time_zone: GMT